pipeline {
    agent any

    stages {
        stage('Git checkout') {
            steps {
                //checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'git-creds', url: 'https://github.com/srinivasabreddy1989/javahomehiring.git']])
                //git branch: 'main', credentialsId: 'git-creds', url: 'https://github.com/srinivasabreddy1989/hiring1.git'
                //git credentialsId: 'github-username-password', url: 'https://github.com/srinivasabreddy1989/hiring1.git'
                //git 'https://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@github.com/srinivasabreddy1989/hiring1.git'
                //create jenkins crediential with username and password user=nonavailable user password=personnal access token
                git credentialsId: 'github-user-token', url: 'https://github.com/srinivasabreddy1989/hiring1.git'
            }
        }
        stage('Git package') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Apache deply') {
            steps {
               sshagent(['Tomcat-creds']) {
                    //sh "scp -o StrictHostKeyChecking=no target/*.war ec2-user@172.31.31.68:/opt/tomcat9/webapps/"
                    //sh "ssh ec2-user@172.31.31.68 /opt/tomcat9/bin/shutdown.sh"
                    //sh "ssh ec2-user@172.31.31.68 /opt/tomcat9/bin/startup.sh"
                    echo "success"
                }
            }
        }
    }
}
