pipeline {
    agent any

    stages {
        stage('Git checkout') {
            steps {
                //checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'git-creds', url: 'https://github.com/srinivasabreddy1989/javahomehiring.git']])
                //git branch: 'main', credentialsId: 'git-creds', url: 'https://github.com/srinivasabreddy1989/hiring1.git'
                //git credentialsId: 'github-username-password', url: 'https://github.com/srinivasabreddy1989/hiring1.git'
                //git 'https://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@github.com/srinivasabreddy1989/hiring1.git'
                //create jenkins crediential with username and password user=nonavailable user password=personnal access token
                git credentialsId: 'github-user-token', url: 'https://github.com/srinivasabreddy1989/hiring1.git'
            }
        }
        stage('Git package') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Apache deply') {
            steps {
               sshagent(['Tomcat-creds']) {
                    //sh "scp -o StrictHostKeyChecking=no target/*.war ec2-user@172.31.31.68:/opt/tomcat9/webapps/"
                    //sh "ssh ec2-user@172.31.31.68 /opt/tomcat9/bin/shutdown.sh"
                    //sh "ssh ec2-user@172.31.31.68 /opt/tomcat9/bin/startup.sh"
                    echo "success"
                }
            }
        }
    }
    // sending email notifications for success and failure
            post {
                success {
                    emailext to: "srinivasa20071989@gmail.com",
                    subject: "jenkins build:${currentBuild.currentResult}: ${env.JOB_NAME}",
                    body: "${currentBuild.currentResult}: Job ${env.JOB_NAME}\nMore Info can be found here: ${env.BUILD_URL}"
        }
                failure {
                    emailext to: "srinivasa20071989@gmail.com",
                    subject: "jenkins build:${currentBuild.currentResult}: ${env.JOB_NAME}",
                    body: "${currentBuild.currentResult}: Job ${env.JOB_NAME}\nMore Info can be found here: ${env.BUILD_URL}"
                }
            }
            // Slack notification for success and failure
            post {
                success {
                    slackSend channel: '#czv', color: 'green', failOnError: true, message: "${currentBuild.currentResult}: Job ${env.JOB_NAME}\nMore Info can be found here: ${env.BUILD_URL}", tokenCredentialId: 'slack-token'
            }
                failure {
                    slackSend channel: '#czv', color: 'red', failOnError: true, message: "${currentBuild.currentResult}: Job ${env.JOB_NAME}\nMore Info can be found here: ${env.BUILD_URL}", tokenCredentialId: 'slack-token'
                }
            }
}
