pipeline {
    agent any

    stages {
        stage('git checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/srinivasabreddy1989/hiring.git']])
                echo "git checkout executed succesfully"
                //git branch: 'main', url: 'https://github.com/srinivasabreddy1989/hiring.git'
                //echo "checkout using git option"
                
            }
        }
        stage('maven build') {
            steps {
                // withMaven(globalMavenSettingsConfig: '--- Use system default settings or file path ---', jdk: '--- Use system default JDK ---', maven: '--- Use system default Maven ---', mavenSettingsConfig: '--- Use system default settings or file path ---') {
                //  sh "mvn clean package"
                // }
                withMaven() {
                    sh 'mvn clean package' 
                }
                // echo "Another way"
                // sh 'mvn clean package'
                
            }
        }
    }
}
