pipeline {
    agent any

    stages {
        stage('Git checkout') {
            steps {
                //checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'git-creds', url: 'https://github.com/srinivasabreddy1989/javahomehiring.git']])
                git branch: 'main', credentialsId: 'git-creds', url: 'https://github.com/srinivasabreddy1989/javahomehiring.git'
            }
        }
        stage('Git package') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Apache deply') {
            steps {
               sshagent(['Tomcat-creds']) {
                    sh "scp -o StrictHostKeyChecking=no target/*.war ec2-user@172.31.31.68:/opt/tomcat9/webapps/"
                    sh "ssh ec2-user@172.31.31.68 /opt/tomcat9/bin/shutdown.sh"
                    sh "ssh ec2-user@172.31.31.68 /opt/tomcat9/bin/startup.sh"
                }
            }
        }
    }
    post {
        success {
            emailext to: "srinivasa20071989@gmail.com",
            subject: "jenkins build:${currentBuild.currentResult}: ${env.JOB_NAME}",
            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME}\nMore Info can be found here: ${env.BUILD_URL}"
  }
  failure {
    emailext to: "srinivasa20071989@gmail.com",
    subject: "jenkins build:${currentBuild.currentResult}: ${env.JOB_NAME}",
    body: "${currentBuild.currentResult}: Job ${env.JOB_NAME}\nMore Info can be found here: ${env.BUILD_URL}"
  }
}
}
